name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Archive
        run: |
          mkdir -p gbn-${GITHUB_REF_NAME}
          cp gbn LICENSE README.md install.sh gbn-${GITHUB_REF_NAME}/
          tar czf gbn-${GITHUB_REF_NAME}.tar.gz gbn-${GITHUB_REF_NAME}
          sha256sum gbn-${GITHUB_REF_NAME}.tar.gz > gbn-${GITHUB_REF_NAME}.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gbn-*.tar.gz
            gbn-*.tar.gz.sha256
          generate_release_notes: true
          draft: false
          prerelease: false

  update-homebrew-formula:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: muneebshahid/homebrew-gbn
          token: ${{ secrets.HOMEBREW_TAP_TOKEN || secrets.GITHUB_TOKEN }}
          path: homebrew-gbn

      - name: Download release assets
        run: |
          curl -sL https://github.com/${{ github.repository }}/archive/refs/tags/${GITHUB_REF_NAME}.tar.gz -o release.tar.gz
          SHA256=$(sha256sum release.tar.gz | cut -d' ' -f1)
          echo "SHA256=${SHA256}" >> $GITHUB_ENV

      - name: Update Homebrew Formula
        run: |
          cd homebrew-gbn
          sed -i "s/PLACEHOLDER_SHA256/${SHA256}/" Formula/gbn.rb
          sed -i "s|refs/tags/v[0-9.]*|refs/tags/${GITHUB_REF_NAME}|" Formula/gbn.rb

      - name: Commit and Push Formula Update
        run: |
          cd homebrew-gbn
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add Formula/gbn.rb
          git commit -m "Update formula for ${GITHUB_REF_NAME}"
          git push